### ISSUE TITLE
error when write channelId 

### ISSUE THREAD

**Issue by abora97** [MindorksOpenSource/NYBus#15]
Compilation failed; see the compiler error output for details.

i have error here 
  @Subscribe(**channelId** = Channel.ONE)
    public void onGetMovie(Movie mMovie) {
        loadMovie(mMovie);
    }

**Comment by amitshekhariitbhu** [comment]
I think you are importing the wrong subscribe annotation. Check the import of the subscribe

**Comment by abora97** [comment]
yes it's work 
thank you 😄 😄

**Comment by abora97** [comment]
@com.mindorks.nybus.annotation.Subscribe(channelId = Channel.ONE)
    public void onGetMovie(Movie mMovie) {
        loadMovie(mMovie);
    }
